### PR TITLE
feat: Implemented hot reloading #20

### PR DESCRIPTION
**Pull request by Muhammad-Shahid-Jamal**
- [x] hot reloading implemented using concurrently package 
- [x] readme.md file also update with new command to run that.

### CODE REVIEW

**Comment by Muhammad-Shahid-Jamal** [comment]
@jenniferabowd  kindly review it thanks

**Comment by jenniferabowd** [comment]
@Muhammad-Shahid-Jamal yes. I'm working right now, but will check it out once I have some time tonight.

**Comment by jenniferabowd** [comment]
Hi, unfortunately running commands concurrently is not hot reloading. Hot reloading refreshes the page to show the latest changes, but concurrently only allows you to run two commands at the same time. Would you mind implementing hot reloading? 

These links will be helpful for adding in hot reloading:
[Webpack Hot Module Replacement](https://webpack.js.org/guides/hot-module-replacement/)
[gaearon/react-hot-loader](https://github.com/gaearon/react-hot-loader#getting-started)

**Comment by Muhammad-Shahid-Jamal** [comment]
> Hi, unfortunately running commands concurrently is not hot reloading. Hot reloading refreshes the page to show the latest changes, but concurrently only allows you to run two commands at the same time. Would you mind implementing hot reloading?
> 
> These links will be helpful for adding in hot reloading: [Webpack Hot Module Replacement](https://webpack.js.org/guides/hot-module-replacement/) [gaearon/react-hot-loader](https://github.com/gaearon/react-hot-loader#getting-started)

Yeh sure I will try it push that code as well

**Comment by jenniferabowd** [comment]
Hi I realized this completes the task for https://github.com/jenniferabowd/jest_webpack_example/issues/21, so I'll merge this in, assign that ticket to you, and close it. Do you still want to the hot reloading one too?

**Review by jenniferabowd — APPROVED** [review]

**Comment by Muhammad-Shahid-Jamal** [comment]
> Hi I realized this completes the task for #21, so I'll merge this in, assign that ticket to you, and close it. Do you still want to the hot reloading one too?

Yeh sure i wanna try it

**Pull request merged**
