### PR TITLE
Updated Webpack

### PR DESCRIPTION
**Pull request by NazimFilzer**
Hey have Updated it.. If any more issues please lemme Know🙂

### CODE REVIEW

**Comment by jenniferabowd** [comment]
Hi, I'm sorry to do this, but this isn't what I had in mind. I'm pretty sure updating Webpack is going to break a bunch of stuff. Did you verify this isn't breaking on `npm start` or `npm test`? Also, I think to make this change, there should be two folders, one folder for Webpack 5 and the other for Webpack 2. However, if updating Webpack isn't breaking things, then that isn't needed.

**Comment by NazimFilzer** [comment]
Ohh Sorry... Had no idea about that... The code is Breaking n I have no idea 😓. I will be closing this PR... Sorry for wasting ur time

**Comment by jenniferabowd** [comment]
No worries! Don't feel bad! You gave it a try! Sorry for not being more clear on the issue ticket! Do you want to work on doing this? I suspect this will relatively be a heavy lift.

**Comment by NazimFilzer** [comment]
Ya.. I am more of a Backend Dev and haven't worked with this before.. So I wont be continuing

**Comment by jenniferabowd** [comment]
No worries! You gave it a try!

**Pull request closed without merging**
