### PR TITLE
Update React 16 → 18

### LINKED ISSUE #7: Upgrade React version
Hi, this example has become a bit stale. I'm hoping someone can help modernize this example to help others during Hacktoberfest. If it doesn't happen, that is okay, but maybe this can be a good chance for someone to participate. I'm making several tickets to help break this up into chunks. I'm happy to help people, but I don't have much time to re-write this code.

It would be really helpful for someone to upgrade this to the current version of React.

### PR DESCRIPTION
**Pull request by brandonmcconnell**
Resolves #7

Updated React from v16 to v18.

I did see the warnings about peer dependencies you mentioned, @jenniferabowd, however, I saw those both when upgrading to v17 and then to v18.

Although I saw these warnings, the vulnerability counts remained the same, and the project appears to function the same as it did before. Is this okay for this PR, or is there more work required for this issue?

### CODE REVIEW

**Comment by brandonmcconnell** [comment]
@jenniferabowd Never mind! I managed to take care of those peer dependency warnings as well by updating…
* `react-test-renderer`
* `react-redux`
* `redux`

So this would be the solution to update everything this PR accomplishes in a single command:
```bash
npm install react@latest react-dom@latest react-test-renderer@latest react-redux@latest redux@latest
```

I just split it into 2 different commits 🙂

**Comment by jenniferabowd** [comment]
@brandonmcconnell if you are doing this for Hacktoberfest, feel free to split up the PR since it is addressing several issues.

**Comment by brandonmcconnell** [comment]
@jenniferabowd Sure, I'll do that. Thanks!

**Review by jenniferabowd — APPROVED** [review]

**Comment by jenniferabowd** [comment]
Oops! I already merged it! However, I see you assigned yourself a few things.

**Comment by brandonmcconnell** [comment]
@jenniferabowd No worries!

**Pull request merged**
