### PR TITLE
Remove server

### LINKED ISSUE #10: Remove server
This example is very convoluted. I think we can just remove the server to simplify it.

### PR DESCRIPTION
**Pull request by brandonmcconnell**
Resolves #10

### CODE REVIEW

**Review by jenniferabowd — APPROVED** [review]

**Comment by jenniferabowd** [comment]
@brandonmcconnell so I didn't test this before merging it. I'm seeing a bunch of errors. First, breaking this isn't the end of the world. Would you prefer I trust the process and merge in all your code before testing or I go in and fix it?
Screen Shot 2022-10-14 at 7 53 01 PM

**Comment by jenniferabowd** [comment]
In the meantime, I'm going to work on fixing it.

**Comment by jenniferabowd** [comment]
Ehhh, I'm going to just trust the process. I can always revert!

**Comment by jenniferabowd** [comment]
@brandonmcconnell would you mind checking out the latest code changes? Is it working for you? I've merged everything in using the order you recommended.

**Comment by brandonmcconnell** [comment]
Yup working on my end sprout any errors and the Jest test passes, and Webpack builds without any new or serious complaints.

Have you tried clearing out and reinstalling all your node_modules? TONS of changes there.

To run the server locally now, I run these two commands:
* `npm run watch`
* `npm start`

Happy to get on a call Monday to troubleshoot!

**Comment by jenniferabowd** [comment]
Hmmm, when you go to localhost do you see the list of presidents? I tried clearing out my node modules and clearing the cache there. It is still broken. What version of NPM are you using? I'm on `8.19.2`.

**Comment by brandonmcconnell** [comment]
@jenniferabowd I'll check when I'm back at my computer. Are you running both the build/watch script (either one should work) and then the start script?

**Comment by jenniferabowd** [comment]
Ohhhhh! I was only running one at a time! I’ll test it out with both in the morning.

**Comment by jenniferabowd** [comment]
Yup! That was it! Sorry about that! Everything is great! Thank you so much for all of your help on this! I really appreciate it!

**Comment by brandonmcconnell** [comment]
@jenniferabowd No worries at all! Yeah, it may be worth opening another ticket for that, or two—
* single command for build, watch, and start
* implement hot reloading

I started looking into both of these during my changes, but that rabbit hole started getting fairly deep, so I halted my work on it. I could probably circle back in a week or two to figure that out.

**Comment by jenniferabowd** [comment]
Honestly, I think it is totally up to you. I personally feel you have done a lot and it is fine to leave it. I also think I should create a few tickets for it. I know when I was trying to find things to do for Hacktoberfest, it was a struggle just to find unclaimed issues. I spent literally hours looking for issues I could tackle. I ended up creating a few PRs, but the maintainers didn't merge them in yet. I got annoyed and decided to try to help out by being a maintainer and reviving this ancient project that has value. So this could be a good opportunity for more people to help out during Hacktoberfest.

**Comment by brandonmcconnell** [comment]
Makes sense! Maybe create the ticket and if no one else jumps in and figures those out by the end of Hacktoberfest, I'd be happy to revisit it 🙂

Re the hot-reloading, there are several instructions on these links which should be all I need to get it up and running  when I revisit it—
* [Webpack Hot Module Replacement](https://webpack.js.org/guides/hot-module-replacement/)
* [gaearon/react-hot-loader](https://github.com/gaearon/react-hot-loader#getting-started)

Given the current setup, you might only need to use the latter, [gaearon/react-hot-loader](https://github.com/gaearon/react-hot-loader#getting-started). 👏🏼

**Pull request merged**
